print ("L            U           U")
print ("L            U           U")
print ("L            U           U")
print ("L            U           U")
print ("L            U           U")
print ("L            U           U")
print ("L            U           U")
print ("LLLLLLLLL    UUUUUUUUUUUUU")